services:
  - type: web
    name: springboot-shopapp
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://<neon_host>:5432/<db_name>?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: <username>
      - key: SPRING_DATASOURCE_PASSWORD
        value: <password>
